### ISSUE TITLE
Add config option to use libotr instead of potr as backend

### ISSUE THREAD

**Issue by Kilobyte22** [mmb/weechat-otr#129]
Using Pure Python OTR might make things pretty easy, but it does violate the number one concept of crypto: Don't roll your own crypto. Furthermore it actually states in it's README that you should not rely on it. While i can understand that not everyone wants to install libotr, it would be a good idea to provide an option to select a backend, possibly defaulting to using libotrwhen present and falling back to potr.

**Comment by tribut** [comment]
As far as I'm aware there is no usable python wrapper for libotr currently. So even if we wanted to do this, we currently would not be able to.

**Comment by fauno** [comment]
did empathy implement otr? iirc it's python too

**Comment by tribut** [comment]
Don't think OTR support ever landed in Empathy. Anyhow, Empathy is written in C.

**Comment by mmb** [comment]
This issue has some details about writing a Python wrapper for libotr:

https://github.com/python-otr/pure-python-otr/issues/53

I believe @afflux put the warning in the README because it is not widely used. I'm willing to devote some time to adding more tests to and improving Pure Python OTR. The codebase is around 2000 lines total and uses PyCrypto for some of the low level crypto.

**Comment by anarcat** [comment]
can't weechat extensions be in any language? some plugins are in C, wouldn't that be a more logical way of implementing OTR support?

**Comment by PMaynard** [comment]
@anarcat  Yep 

@mmb - I see no advantage to continue with  Pure Python OTR. Would there not be a way to create a  python binding to libotr. That way you'd have more eyes of the crypto, and not have to roll your own.

**Comment by mmb** [comment]
I understand the desire to use code that has had more eyes and mileage on it. libotr is the standard and the best choice.

Using libotr would require either:

1) Python bindings for libotr. @afflux went down this road and then wrote pure python otr (see https://github.com/python-otr/pure-python-otr/issues/53#issuecomment-50081843). weechat-otr started off using afflux's libotr wrapper and then switched to pure python otr because it was easier to use and it worked better.

2) not using Python. This would be a complete rewrite so it makes more sense as a new project. If users really want to use libotr I would recommend writing a native WeeChat plugin that uses libotr directly like the irssi plugin.

If anyone writes good Python bindings for libotr we will definitely consider switching to them.

**Comment by Mikaela** [comment]
>  If users really want to use libotr I would recommend writing a native WeeChat plugin that uses libotr directly like the irssi plugin.

https://github.com/weechat/weechat/issues/298

**Comment by koolfy** [comment]
At that point, why not push for a native support for OTR through libotr built in weechat?
I thank that would be the best solution.

I'm actually ok with using using weechat-otr.py as a debug tool for potr :p
A native OTR support could even probably go beyond what this plugin could dream of.
